Traceback (most recent call last):
  File "/home/salva/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/salva/.local/lib/python3.8/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/salva/.local/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/salva/.local/lib/python3.8/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/salva/.local/lib/python3.8/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/salva/.local/lib/python3.8/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Requirements
!pip install -q pyomo
import pyomo.environ as pe
!apt-get install -y -qq glpk-utils
glpk = pe.SolverFactory('glpk', executable='/usr/bin/glpsol')
# Model
m = pe.ConcreteModel()
# Variables
m.x1 = pe.Var(within=pe.NonNegativeReals,bounds=(0,4))
m.x2 = pe.Var(within=pe.NonNegativeReals,bounds=(0,6))
# Objective function
m.obj = pe.Objective(expr = 3*m.x1 + 5*m.x2,sense=pe.maximize)
# Constraints
m.con = pe.Constraint(expr = 3*m.x1 + 2*m.x2 <= 18)
# Solve problem using GLPK solver
glpk.solve(m).write()
# Print results
print('x1 =',m.x1.value)
print('x2 =',m.x2.value)
print('Optimal value =',m.obj())
------------------

----- stdout -----
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
----- stdout -----
WARNING: Failed to create solver with name '_glpk_shell': Failed to set
    executable for solver glpk. File with name=/usr/bin/glpsol either does not
    exist or it is not executable. To skip this validation, call
    set_executable with validate=False.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[1], line 16[0m
[1;32m     14[0m m[38;5;241m.[39mcon [38;5;241m=[39m pe[38;5;241m.[39mConstraint(expr [38;5;241m=[39m [38;5;241m3[39m[38;5;241m*[39mm[38;5;241m.[39mx1 [38;5;241m+[39m [38;5;241m2[39m[38;5;241m*[39mm[38;5;241m.[39mx2 [38;5;241m<[39m[38;5;241m=[39m [38;5;241m18[39m)
[1;32m     15[0m [38;5;66;03m# Solve problem using GLPK solver[39;00m
[0;32m---> 16[0m [43mglpk[49m[38;5;241;43m.[39;49m[43msolve[49m[43m([49m[43mm[49m[43m)[49m[38;5;241m.[39mwrite()
[1;32m     17[0m [38;5;66;03m# Print results[39;00m
[1;32m     18[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mx1 =[39m[38;5;124m'[39m,m[38;5;241m.[39mx1[38;5;241m.[39mvalue)

File [0;32m~/.local/lib/python3.8/site-packages/pyomo/opt/base/solvers.py:110[0m, in [0;36mUnknownSolver.solve[0;34m(self, *args, **kwds)[0m
[1;32m    108[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21msolve[39m([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds):
[1;32m    109[0m [38;5;250m    [39m[38;5;124;03m"""Perform optimization and return an SolverResults object."""[39;00m
[0;32m--> 110[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_solver_error[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43msolve[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/.local/lib/python3.8/site-packages/pyomo/opt/base/solvers.py:127[0m, in [0;36mUnknownSolver._solver_error[0;34m(self, method_name)[0m
[1;32m    126[0m     [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21m_solver_error[39m([38;5;28mself[39m, method_name):
[0;32m--> 127[0m         [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"""[39m[38;5;124mAttempting to use an unavailable solver.[39m
[1;32m    128[0m 
[1;32m    129[0m [38;5;124mThe SolverFactory was unable to create the solver [39m[38;5;124m"[39m[38;5;132;01m%s[39;00m[38;5;124m"[39m
[1;32m    130[0m [38;5;124mand returned an UnknownSolver object.  This error is raised at the point[39m
[1;32m    131[0m [38;5;124mwhere the UnknownSolver object was used as if it were valid (by calling[39m
[1;32m    132[0m [38;5;124mmethod [39m[38;5;124m"[39m[38;5;132;01m%s[39;00m[38;5;124m"[39m[38;5;124m).[39m
[1;32m    133[0m 
[1;32m    134[0m [38;5;124mThe original solver was created with the following parameters:[39m
[1;32m    135[0m [38;5;130;01m\t[39;00m[38;5;124m"""[39m [38;5;241m%[39m ( [38;5;28mself[39m[38;5;241m.[39mtype, method_name )
[1;32m    136[0m [38;5;241m+[39m [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;130;01m\t[39;00m[38;5;124m"[39m[38;5;241m.[39mjoin([38;5;124m"[39m[38;5;132;01m%s[39;00m[38;5;124m: [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m [38;5;241m%[39m i [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28msorted[39m([38;5;28mself[39m[38;5;241m.[39m_kwds[38;5;241m.[39mitems()))
[1;32m    137[0m [38;5;241m+[39m [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;130;01m\t[39;00m[38;5;124m_args: [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m [38;5;241m%[39m ( [38;5;28mself[39m[38;5;241m.[39m_args, )
[1;32m    138[0m [38;5;241m+[39m [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;130;01m\t[39;00m[38;5;124moptions: [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m [38;5;241m%[39m ( [38;5;28mself[39m[38;5;241m.[39moptions, ) )

[0;31mRuntimeError[0m: Attempting to use an unavailable solver.

The SolverFactory was unable to create the solver "_glpk_shell"
and returned an UnknownSolver object.  This error is raised at the point
where the UnknownSolver object was used as if it were valid (by calling
method "solve").

The original solver was created with the following parameters:
	executable: /usr/bin/glpsol
	type: _glpk_shell
	_args: ()
	options: {}

